### ISSUE TITLE
Using LivingDoc with JEE applications

### ISSUE THREAD

**Issue by evictoria** [testIT-LivingDoc/livingdoc-core#14]
Hi,

We created fixtures inside our JEE application. These fixtures need to call EJB's but it seem it doesn't work since the fixtures are not inside the EJB container. Is the only work-around for this is to call the webservices of our JEE application from the fixtures? Thanks..

**Comment by jaspreetParhar** [comment]
Hi evictoria,

this is by design. A fixtures life cycle is controlled by the livingDoc execution code and therefore can't be within the EJB container's life cycle. So you have to call the webservices of your JEE applications from the fixtures.

**Comment by benhamidene** [comment]
Hi, 
a very important tet automation principle : SEPARATE test and production code ! NEVER EVER mix them ;)

You could use generic test fassades to acces your ejbs, that you only deploy to your testing environments
