### ISSUE TITLE
LivingDoc Documentation License

### ISSUE THREAD

**Issue by wattazoum** [testIT-LivingDoc/livingdoc-core#6]
Hi, 

First of all, thank you for having retrieve most of GreenPepper useful documentation.
After the loss of the original one, I am worrying about the availability of projects documentation now.

Is the documentation opensource ? 
Can it be forked modified, and the modification suggested ? 
How do we retrieve it ?

**Comment by benhamidene** [comment]
Hi,

we did not retrieve the documentation. We became an older snapshot from the GreenPepper Team and they allowed us to use it. Then we reworked and extended it.

The documentation (incl.pictures and snapshts) is not open source as it is not part of the GreenPepper Open Source project.

You can suggest modfication here or by writing comments on the space there. 

Anyway LivingDoc is still compatible to GreenPepper . So the documentation may be valid for both of them.

Regards.
Anis

**Comment by wattazoum** [comment]
Hi, 

Thank you for your prompt answer. 

Regards
wattazoum
